SET FEEDBACK OFF LINESIZE 4000 TRIMSPOOL ON TRIMOUT ON VERIFY OFF ECHO OFF PAGESIZE 4000
SPOOL /tmp/get_proj_growth.sql
select 'SELECT TO_CHAR(TRUNC(TIMEPOINT),''YYYYMMDD'') "DATE", SPACE_USAGE/1024 "KB_USED", SPACE_ALLOC/1024 "KB ALLOC", QUALITY
FROM TABLE(DBMS_SPACE.OBJECT_GROWTH_TREND('''||OWNER||''','''||OBJECT_NAME||''','''||OBJECT_TYPE||''',NULL,NULL,SYSTIMESTAMP+30,INTERVAL ''1'' DAY))
ORDER BY TIMEPOINT;' from dba_objects where owner = 'TRENTADM';
SPOOL OFF
