SHUTDOWN ABORT;
SET ECHO ON
SPOOL cr_PLIASON.log
STARTUP NOMOUNT
CREATE DATABASE "PLIASON"
    CONTROLFILE REUSE
    MAXLOGFILES         6
    MAXLOGMEMBERS       2
    MAXDATAFILES        40
    MAXINSTANCES        1
    MAXLOGHISTORY       300
    CHARACTER SET WE8ISO8859P1
    NATIONAL CHARACTER SET UTF8
    NOARCHIVELOG
    	DATAFILE 
		'F:\ORACLE\920\DATABASE\PLIASON\DATA\PLIASON_system_01.dbf' 
		SIZE 400M REUSE EXTENT MANAGEMENT LOCAL
    DEFAULT TEMPORARY TABLESPACE TEMPORARY
	TEMPFILE 
		'F:\ORACLE\920\DATABASE\PLIASON\DATA\PLIASON_temporary_01.dbf' 
		SIZE 350M REUSE
    UNDO TABLESPACE UNDO 
	DATAFILE 'F:\ORACLE\920\DATABASE\PLIASON\DATA\PLIASON_undo_01.dbf' 
		SIZE 300M REUSE
    LOGFILE
    GROUP  1 'E:\ORACLE\920\DATABASE\PLIASON\REDO\PLIASON_redo1a.dbf' size 25M REUSE,
    GROUP  2 'G:\ORACLE\920\DATABASE\PLIASON\REDO\PLIASON_redo2a.dbf' size 25M REUSE,
    GROUP  3 'E:\ORACLE\920\DATABASE\PLIASON\REDO\PLIASON_redo3a.dbf' size 25M REUSE;
